// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: databases.sql

package store

import (
	"context"
)

const getDatabase = `-- name: GetDatabase :one
SELECT id, owner_user_id, engine, db_name, db_user, status, last_error, created_at, updated_at, subscription_id
FROM databases
WHERE id = $1
`

func (q *Queries) GetDatabase(ctx context.Context, id int64) (Database, error) {
	row := q.db.QueryRowContext(ctx, getDatabase, id)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Engine,
		&i.DbName,
		&i.DbUser,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubscriptionID,
	)
	return i, err
}

const listDatabases = `-- name: ListDatabases :many
SELECT id, owner_user_id, engine, db_name, db_user, status, last_error, created_at, updated_at, subscription_id
FROM databases
ORDER BY id
`

func (q *Queries) ListDatabases(ctx context.Context) ([]Database, error) {
	rows, err := q.db.QueryContext(ctx, listDatabases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Database
	for rows.Next() {
		var i Database
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Engine,
			&i.DbName,
			&i.DbUser,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SubscriptionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDatabaseActive = `-- name: MarkDatabaseActive :exec
UPDATE databases
SET
    status = 'active',
    last_error = '',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDatabaseActive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markDatabaseActive, id)
	return err
}

const markDatabaseFailed = `-- name: MarkDatabaseFailed :exec
UPDATE databases
SET
    status = 'failed',
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkDatabaseFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkDatabaseFailed(ctx context.Context, arg MarkDatabaseFailedParams) error {
	_, err := q.db.ExecContext(ctx, markDatabaseFailed, arg.ID, arg.LastError)
	return err
}

const upsertDatabaseIntent = `-- name: UpsertDatabaseIntent :one
INSERT INTO databases (
    owner_user_id,
    subscription_id,
    engine,
    db_name,
    db_user,
    status,
    last_error
) VALUES (
    $1,
    (SELECT id FROM subscriptions WHERE customer_user_id = $1 AND status = 'active' LIMIT 1),
    $2,
    $3,
    $4,
    'pending',
    ''
)
ON CONFLICT (db_name) DO UPDATE
SET
    owner_user_id = EXCLUDED.owner_user_id,
    subscription_id = EXCLUDED.subscription_id,
    engine = EXCLUDED.engine,
    db_user = EXCLUDED.db_user,
    status = 'pending',
    last_error = '',
    updated_at = now()
RETURNING id, owner_user_id, engine, db_name, db_user, status, last_error, created_at, updated_at, subscription_id
`

type UpsertDatabaseIntentParams struct {
	OwnerUserID int64
	Engine      string
	DbName      string
	DbUser      string
}

func (q *Queries) UpsertDatabaseIntent(ctx context.Context, arg UpsertDatabaseIntentParams) (Database, error) {
	row := q.db.QueryRowContext(ctx, upsertDatabaseIntent,
		arg.OwnerUserID,
		arg.Engine,
		arg.DbName,
		arg.DbUser,
	)
	var i Database
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Engine,
		&i.DbName,
		&i.DbUser,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SubscriptionID,
	)
	return i, err
}
