// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"time"
)

type AccountQuota struct {
	UserID            int64
	MaxSites          int32
	MaxDatabases      int32
	StorageMb         int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	MaxBackups        int32
	BackupStorageMb   int32
	SiteDiskQuotaMb   int32
	PhpFpmMaxChildren int32
	PhpMemoryMb       int32
}

type AdminerToken struct {
	ID          int64
	OwnerUserID int64
	TokenHash   string
	ExpiresAt   time.Time
	UsedAt      sql.NullTime
	CreatedAt   time.Time
}

type Backup struct {
	ID             int64
	OwnerUserID    int64
	SiteID         sql.NullInt64
	TargetKind     string
	TargetName     string
	Status         string
	ArchivePath    string
	SizeBytes      int64
	ChecksumSha256 string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubscriptionID sql.NullInt64
}

type Database struct {
	ID             int64
	OwnerUserID    int64
	Engine         string
	DbName         string
	DbUser         string
	Status         string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubscriptionID sql.NullInt64
}

type DnsZone struct {
	ID          int64
	OwnerUserID int64
	SiteID      int64
	Domain      string
	Address     string
	Serial      int64
	Status      string
	ZonePath    string
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Plan struct {
	ID                  int64
	Name                string
	Description         string
	PriceCents          sql.NullInt32
	DiskMb              int32
	MaxSites            int32
	MaxDatabases        int32
	BandwidthMb         int32
	MaxMailboxes        int32
	AllowSsh            bool
	AllowDns            bool
	BackupRetentionDays int32
	PhpAllowlist        string
	PhpFpmMaxChildren   int32
	PhpMemoryMb         int32
	SiteDiskQuotaMb     int32
	MaxBackups          int32
	BackupStorageMb     int32
	IsActive            bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

type ReconciliationRun struct {
	ID          int64
	OwnerUserID int64
	Status      string
	SitesTotal  int32
	SitesOk     int32
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type RestoreRun struct {
	ID          int64
	OwnerUserID int64
	BackupID    sql.NullInt64
	TargetName  string
	Status      string
	RestoredAt  sql.NullTime
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Session struct {
	TokenHash string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
}

type Setting struct {
	ID                   bool
	OversellPolicy       string
	ServerDiskCapacityMb int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type Site struct {
	ID             int64
	OwnerUserID    int64
	Username       string
	Domain         string
	PhpVersion     string
	Status         string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	TlsStatus      string
	TlsIssuer      string
	TlsCertPath    string
	TlsKeyPath     string
	TlsExpiresAt   sql.NullTime
	TlsLastError   string
	SubscriptionID sql.NullInt64
}

type Subscription struct {
	ID             int64
	CustomerUserID int64
	ResellerUserID sql.NullInt64
	PlanID         int64
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type User struct {
	ID           int64
	Email        string
	PasswordHash string
	Role         string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type WebmailHost struct {
	ID          int64
	OwnerUserID int64
	SiteID      int64
	Hostname    string
	Status      string
	ConfigPath  string
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
