// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type AccountQuota struct {
	UserID            int64
	MaxSites          int32
	MaxDatabases      int32
	StorageMb         int32
	CreatedAt         time.Time
	UpdatedAt         time.Time
	MaxBackups        int32
	BackupStorageMb   int32
	SiteDiskQuotaMb   int32
	PhpFpmMaxChildren int32
	PhpMemoryMb       int32
}

type AddonPlan struct {
	ID                  int64
	ResellerID          sql.NullInt64
	Name                string
	Description         string
	DiskMb              int32
	MaxSites            int32
	MaxDatabases        int32
	BandwidthMb         int32
	MaxMailboxes        int32
	BackupRetentionDays int32
	PhpAllowlist        string
	PhpFpmMaxChildren   int32
	PhpMemoryMb         int32
	SiteDiskQuotaMb     int32
	MaxBackups          int32
	BackupStorageMb     int32
	AllowSsh            bool
	AllowDns            bool
	IsActive            bool
	Revision            int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	MaxSubdomains       int32
	MaxDomainAliases    int32
	MaxFtpAccounts      int32
	AllowTls            bool
	AllowBackups        bool
	AllowPhpSettings    bool
	ServicePresets      json.RawMessage
	HostingPolicy       json.RawMessage
}

type AdminerToken struct {
	ID          int64
	OwnerUserID int64
	TokenHash   string
	ExpiresAt   time.Time
	UsedAt      sql.NullTime
	CreatedAt   time.Time
}

type ApiIdempotencyRecord struct {
	ID             int64
	ApiKeyID       int64
	IdempotencyKey string
	Method         string
	Path           string
	RequestHash    []byte
	ResponseStatus sql.NullInt32
	ResponseBody   pqtype.NullRawMessage
	CreatedAt      time.Time
	ExpiresAt      time.Time
}

type ApiKey struct {
	ID                 int64
	Name               string
	KeyPrefix          string
	KeySalt            []byte
	KeyHash            []byte
	Scope              string
	IpAllowlist        []pqtype.CIDR
	RateLimitPerMinute int32
	ExpiresAt          sql.NullTime
	RevokedAt          sql.NullTime
	LastUsedAt         sql.NullTime
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type ApplicationInstance struct {
	ID                int64
	SubscriptionID    int64
	SiteID            sql.NullInt64
	Name              string
	Runtime           string
	CatalogSlug       string
	ImageRef          string
	DesiredState      string
	AppliedState      string
	Environment       json.RawMessage
	Healthcheck       json.RawMessage
	ConvergenceStatus string
	LastError         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeleteRequested   bool
}

type ApplicationPort struct {
	ID            int64
	ApplicationID int64
	ContainerPort int32
	HostPort      sql.NullInt32
	Protocol      string
	RouteHost     string
}

type ApplicationVolume struct {
	ID            int64
	ApplicationID int64
	Name          string
	ContainerPath string
	SizeMb        int32
}

type AuditEvent struct {
	ID             int64
	ActorUserID    sql.NullInt64
	CustomerID     sql.NullInt64
	SubscriptionID sql.NullInt64
	Action         string
	TargetType     string
	TargetID       sql.NullInt64
	Metadata       json.RawMessage
	CreatedAt      time.Time
	ActorLabel     sql.NullString
}

type Backup struct {
	ID             int64
	OwnerUserID    int64
	SiteID         sql.NullInt64
	TargetKind     string
	TargetName     string
	Status         string
	ArchivePath    string
	SizeBytes      int64
	ChecksumSha256 string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubscriptionID int64
	CustomerID     int64
	ScheduledFor   sql.NullTime
}

type BillingAccount struct {
	ID                 int64
	SubscriptionID     int64
	PublicID           string
	ExternalRef        string
	ProviderResellerID sql.NullInt64
	PrimarySiteID      sql.NullInt64
	ProvisioningState  string
	OverLimit          bool
	LastError          string
	CancelledAt        sql.NullTime
	PurgeEligibleAt    sql.NullTime
	PurgeRequestedAt   sql.NullTime
	TerminatedAt       sql.NullTime
	CreatedByApiKeyID  sql.NullInt64
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type BillingWebhookOutbox struct {
	ID               int64
	DeliveryID       string
	BillingAccountID int64
	EventType        string
	DedupeKey        string
	Payload          json.RawMessage
	Status           string
	Attempts         int32
	ResponseStatus   sql.NullInt32
	LastError        string
	SentAt           sql.NullTime
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Customer struct {
	ID          int64
	LoginUserID sql.NullInt64
	Email       string
	DisplayName string
	Company     string
	Status      string
	Notes       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ResellerID  sql.NullInt64
}

type CustomerLoginToken struct {
	ID               int64
	BillingAccountID int64
	UserID           int64
	TokenHash        []byte
	ExpiresAt        time.Time
	UsedAt           sql.NullTime
	CreatedAt        time.Time
}

type Database struct {
	ID             int64
	OwnerUserID    int64
	Engine         string
	DbName         string
	DbUser         string
	Status         string
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	SubscriptionID int64
	CustomerID     int64
	SiteID         sql.NullInt64
}

type DnsRecord struct {
	ID         int64
	ZoneID     int64
	Host       string
	RecordType string
	Value      string
	Priority   sql.NullInt32
	Ttl        int32
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

type DnsZone struct {
	ID          int64
	OwnerUserID int64
	SiteID      int64
	Domain      string
	Address     string
	Serial      int64
	Status      string
	ZonePath    string
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type MailAlias struct {
	ID           int64
	MailDomainID int64
	LocalPart    string
	Destinations []string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type MailDomain struct {
	ID                int64
	SubscriptionID    int64
	SiteID            sql.NullInt64
	Domain            string
	Enabled           bool
	DkimEnabled       bool
	DmarcPolicy       string
	CatchAll          string
	ConvergenceStatus string
	LastError         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
	DeleteRequested   bool
}

type MailSetting struct {
	ID                  bool
	MailHostname        string
	SmarthostHost       string
	SmarthostPort       int32
	SmarthostUsername   string
	SmarthostPassword   string
	OutboundRateLimit   string
	QueueAlertThreshold int32
	UpdatedAt           time.Time
}

type Mailbox struct {
	ID            int64
	MailDomainID  int64
	LocalPart     string
	QuotaMb       int32
	Enabled       bool
	Autoresponder json.RawMessage
	CreatedAt     time.Time
	UpdatedAt     time.Time
	PasswordHash  string
}

type Notification struct {
	ID              int64
	RecipientUserID sql.NullInt64
	CustomerID      sql.NullInt64
	ResellerID      sql.NullInt64
	SubscriptionID  sql.NullInt64
	Kind            string
	Severity        string
	Title           string
	Body            string
	DedupeKey       string
	ReadAt          sql.NullTime
	ResolvedAt      sql.NullTime
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type NotificationDelivery struct {
	ID             int64
	NotificationID int64
	Channel        string
	Recipient      string
	Status         string
	Attempts       int32
	LastError      string
	SentAt         sql.NullTime
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Plan struct {
	ID                    int64
	Name                  string
	Description           string
	PriceCents            sql.NullInt32
	DiskMb                int32
	MaxSites              int32
	MaxDatabases          int32
	BandwidthMb           int32
	MaxMailboxes          int32
	AllowSsh              bool
	AllowDns              bool
	BackupRetentionDays   int32
	PhpAllowlist          string
	PhpFpmMaxChildren     int32
	PhpMemoryMb           int32
	SiteDiskQuotaMb       int32
	MaxBackups            int32
	BackupStorageMb       int32
	IsActive              bool
	CreatedAt             time.Time
	UpdatedAt             time.Time
	ResellerID            sql.NullInt64
	Revision              int32
	OverusePolicy         string
	DiskWarningPercent    int32
	TrafficWarningPercent int32
	MaxSubdomains         int32
	MaxDomainAliases      int32
	MaxFtpAccounts        int32
	ValidityDays          int32
	HostingEnabled        bool
	DefaultPhpVersion     string
	AllowTls              bool
	AllowBackups          bool
	AllowPhpSettings      bool
	HostingPolicy         json.RawMessage
	ApiSlug               string
}

type PlanServicePreset struct {
	PlanID        int64
	SchemaVersion int32
	Hosting       json.RawMessage
	Php           json.RawMessage
	Mail          json.RawMessage
	Dns           json.RawMessage
	Performance   json.RawMessage
	Logs          json.RawMessage
	Applications  json.RawMessage
	UpdatedAt     time.Time
}

type ReconciliationRun struct {
	ID          int64
	OwnerUserID int64
	Status      string
	SitesTotal  int32
	SitesOk     int32
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ResellerAccount struct {
	ID          int64
	LoginUserID int64
	Email       string
	DisplayName string
	Company     string
	Status      string
	Notes       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ResellerPlan struct {
	ID               int64
	Name             string
	Description      string
	MaxCustomers     int32
	MaxSubscriptions int32
	DiskMb           int32
	MaxSites         int32
	MaxDatabases     int32
	BandwidthMb      int32
	MaxMailboxes     int32
	MaxBackups       int32
	BackupStorageMb  int32
	AllowCustomPlans bool
	AllowSsh         bool
	AllowDns         bool
	IsActive         bool
	CreatedAt        time.Time
	UpdatedAt        time.Time
	MaxSubdomains    int32
	MaxDomainAliases int32
	MaxFtpAccounts   int32
	AllowTls         bool
	AllowBackups     bool
	AllowPhpSettings bool
	HostingPolicy    json.RawMessage
}

type ResellerSubscription struct {
	ID             int64
	ResellerID     int64
	ResellerPlanID int64
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RestoreRun struct {
	ID          int64
	OwnerUserID int64
	BackupID    sql.NullInt64
	TargetName  string
	Status      string
	RestoredAt  sql.NullTime
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ScheduledTask struct {
	ID                int64
	SubscriptionID    int64
	SiteID            sql.NullInt64
	Name              string
	Schedule          string
	Command           string
	WorkingDirectory  string
	TimeoutSeconds    int32
	Enabled           bool
	ConvergenceStatus string
	LastError         string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ScheduledTaskRun struct {
	ID         int64
	TaskID     int64
	Status     string
	ExitCode   sql.NullInt32
	Output     string
	StartedAt  sql.NullTime
	FinishedAt sql.NullTime
	CreatedAt  time.Time
}

type Session struct {
	TokenHash string
	UserID    int64
	ExpiresAt time.Time
	CreatedAt time.Time
	ID        int64
}

type Setting struct {
	ID                   bool
	OversellPolicy       string
	ServerDiskCapacityMb int32
	CreatedAt            time.Time
	UpdatedAt            time.Time
}

type SftpAccessIdentity struct {
	ID             int64
	SubscriptionID int64
	Name           string
	PublicKey      string
	RelativeRoot   string
	Enabled        bool
	LastError      string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type Site struct {
	ID                   int64
	OwnerUserID          int64
	Username             string
	Domain               string
	PhpVersion           string
	Status               string
	LastError            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TlsStatus            string
	TlsIssuer            string
	TlsCertPath          string
	TlsKeyPath           string
	TlsExpiresAt         sql.NullTime
	TlsLastError         string
	SubscriptionID       int64
	CustomerID           int64
	DesiredStatus        string
	DesiredPhpVersion    string
	HttpsRedirect        bool
	DesiredHttpsRedirect bool
	SettingsStatus       string
	SettingsError        string
	TlsAutoRenew         bool
	SystemAccountID      int64
	DocumentRoot         string
}

type SitePolicyOverride struct {
	SiteID        int64
	SchemaVersion int32
	PolicyPatch   json.RawMessage
	UpdatedBy     sql.NullInt64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type SiteTrafficCursor struct {
	SiteID       int64
	DeviceID     int64
	Inode        int64
	ByteOffset   int64
	PeriodStart  time.Time
	TrafficBytes int64
	UpdatedAt    time.Time
}

type StalwartAccount struct {
	Name        interface{}
	Type        string
	Secret      string
	Description string
	Quota       interface{}
}

type StalwartDomain struct {
	Name string
}

type StalwartEmail struct {
	Name    interface{}
	Address interface{}
	Type    string
}

type Subscription struct {
	ID               int64
	CustomerUserID   sql.NullInt64
	ResellerUserID   sql.NullInt64
	PlanID           sql.NullInt64
	Status           string
	CreatedAt        time.Time
	UpdatedAt        time.Time
	CustomerID       int64
	Name             string
	SyncMode         string
	SyncStatus       string
	PlanRevision     int32
	SyncError        string
	SuspensionReason string
	ExpiresAt        sql.NullTime
}

type SubscriptionAddon struct {
	SubscriptionID int64
	AddonPlanID    int64
	CreatedAt      time.Time
}

type SubscriptionEntitlement struct {
	SubscriptionID        int64
	PlanName              string
	DiskMb                int32
	MaxSites              int32
	MaxDatabases          int32
	BandwidthMb           int32
	MaxMailboxes          int32
	AllowSsh              bool
	AllowDns              bool
	BackupRetentionDays   int32
	PhpAllowlist          string
	PhpFpmMaxChildren     int32
	PhpMemoryMb           int32
	SiteDiskQuotaMb       int32
	MaxBackups            int32
	BackupStorageMb       int32
	SourceRevision        int32
	UpdatedAt             time.Time
	OverusePolicy         string
	DiskWarningPercent    int32
	TrafficWarningPercent int32
	MaxSubdomains         int32
	MaxDomainAliases      int32
	MaxFtpAccounts        int32
	ValidityDays          int32
	HostingEnabled        bool
	DefaultPhpVersion     string
	AllowTls              bool
	AllowBackups          bool
	AllowPhpSettings      bool
	ServicePresets        json.RawMessage
	HostingPolicy         json.RawMessage
}

type SubscriptionPolicyOverride struct {
	SubscriptionID int64
	SchemaVersion  int32
	PolicyPatch    json.RawMessage
	UpdatedBy      sql.NullInt64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type SubscriptionSystemAccount struct {
	ID                int64
	SubscriptionID    int64
	Username          string
	HomePath          string
	LinuxUid          sql.NullInt32
	ShellMode         string
	DesiredState      string
	AppliedState      string
	ConvergenceStatus string
	LastError         string
	MigrationStatus   string
	MigrationError    string
	LegacyHomes       json.RawMessage
	MigratedAt        sql.NullTime
	CleanupAfter      sql.NullTime
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SubscriptionUsageCurrent struct {
	SubscriptionID int64
	PeriodStart    time.Time
	SiteBytes      int64
	DatabaseBytes  int64
	BackupBytes    int64
	DiskBytes      int64
	TrafficBytes   int64
	IsComplete     bool
	CollectedAt    time.Time
	LastError      string
}

type SubscriptionUsageHistory struct {
	ID             int64
	SubscriptionID int64
	PeriodStart    time.Time
	SiteBytes      int64
	DatabaseBytes  int64
	BackupBytes    int64
	DiskBytes      int64
	TrafficBytes   int64
	RecordedAt     time.Time
}

type User struct {
	ID            int64
	Email         string
	PasswordHash  string
	Role          string
	CreatedAt     time.Time
	UpdatedAt     time.Time
	LoginDisabled bool
}

type WebmailHost struct {
	ID          int64
	OwnerUserID int64
	SiteID      int64
	Hostname    string
	Status      string
	ConfigPath  string
	LastError   string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
