// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: plans.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const getActiveSubscription = `-- name: GetActiveSubscription :one
SELECT s.id, s.customer_user_id, s.reseller_user_id, s.plan_id, s.status, s.created_at, s.updated_at
FROM subscriptions s
WHERE s.customer_user_id = $1
  AND s.status = 'active'
`

type GetActiveSubscriptionRow struct {
	ID             int64
	CustomerUserID sql.NullInt64
	ResellerUserID sql.NullInt64
	PlanID         sql.NullInt64
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) GetActiveSubscription(ctx context.Context, customerUserID sql.NullInt64) (GetActiveSubscriptionRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveSubscription, customerUserID)
	var i GetActiveSubscriptionRow
	err := row.Scan(
		&i.ID,
		&i.CustomerUserID,
		&i.ResellerUserID,
		&i.PlanID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, name, description, price_cents, disk_mb, max_sites, max_databases, bandwidth_mb,
       max_mailboxes, allow_ssh, allow_dns, backup_retention_days, php_allowlist,
       php_fpm_max_children, php_memory_mb, site_disk_quota_mb, max_backups,
       backup_storage_mb, is_active, created_at, updated_at
FROM plans
WHERE id = $1
`

type GetPlanRow struct {
	ID                  int64
	Name                string
	Description         string
	PriceCents          sql.NullInt32
	DiskMb              int32
	MaxSites            int32
	MaxDatabases        int32
	BandwidthMb         int32
	MaxMailboxes        int32
	AllowSsh            bool
	AllowDns            bool
	BackupRetentionDays int32
	PhpAllowlist        string
	PhpFpmMaxChildren   int32
	PhpMemoryMb         int32
	SiteDiskQuotaMb     int32
	MaxBackups          int32
	BackupStorageMb     int32
	IsActive            bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) GetPlan(ctx context.Context, id int64) (GetPlanRow, error) {
	row := q.db.QueryRowContext(ctx, getPlan, id)
	var i GetPlanRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.DiskMb,
		&i.MaxSites,
		&i.MaxDatabases,
		&i.BandwidthMb,
		&i.MaxMailboxes,
		&i.AllowSsh,
		&i.AllowDns,
		&i.BackupRetentionDays,
		&i.PhpAllowlist,
		&i.PhpFpmMaxChildren,
		&i.PhpMemoryMb,
		&i.SiteDiskQuotaMb,
		&i.MaxBackups,
		&i.BackupStorageMb,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSettings = `-- name: GetSettings :one
SELECT id, oversell_policy, server_disk_capacity_mb, created_at, updated_at
FROM settings
WHERE id = true
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.OversellPolicy,
		&i.ServerDiskCapacityMb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveSubscriptions = `-- name: ListActiveSubscriptions :many
SELECT s.id, s.customer_user_id, s.reseller_user_id, s.plan_id, s.status, s.created_at, s.updated_at
FROM subscriptions s
WHERE s.status = 'active'
ORDER BY s.customer_user_id
`

type ListActiveSubscriptionsRow struct {
	ID             int64
	CustomerUserID sql.NullInt64
	ResellerUserID sql.NullInt64
	PlanID         sql.NullInt64
	Status         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

func (q *Queries) ListActiveSubscriptions(ctx context.Context) ([]ListActiveSubscriptionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveSubscriptionsRow
	for rows.Next() {
		var i ListActiveSubscriptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerUserID,
			&i.ResellerUserID,
			&i.PlanID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlans = `-- name: ListPlans :many
SELECT id, name, description, price_cents, disk_mb, max_sites, max_databases, bandwidth_mb,
       max_mailboxes, allow_ssh, allow_dns, backup_retention_days, php_allowlist,
       php_fpm_max_children, php_memory_mb, site_disk_quota_mb, max_backups,
       backup_storage_mb, is_active, created_at, updated_at
FROM plans
ORDER BY id
`

type ListPlansRow struct {
	ID                  int64
	Name                string
	Description         string
	PriceCents          sql.NullInt32
	DiskMb              int32
	MaxSites            int32
	MaxDatabases        int32
	BandwidthMb         int32
	MaxMailboxes        int32
	AllowSsh            bool
	AllowDns            bool
	BackupRetentionDays int32
	PhpAllowlist        string
	PhpFpmMaxChildren   int32
	PhpMemoryMb         int32
	SiteDiskQuotaMb     int32
	MaxBackups          int32
	BackupStorageMb     int32
	IsActive            bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
}

func (q *Queries) ListPlans(ctx context.Context) ([]ListPlansRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlans)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlansRow
	for rows.Next() {
		var i ListPlansRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.DiskMb,
			&i.MaxSites,
			&i.MaxDatabases,
			&i.BandwidthMb,
			&i.MaxMailboxes,
			&i.AllowSsh,
			&i.AllowDns,
			&i.BackupRetentionDays,
			&i.PhpAllowlist,
			&i.PhpFpmMaxChildren,
			&i.PhpMemoryMb,
			&i.SiteDiskQuotaMb,
			&i.MaxBackups,
			&i.BackupStorageMb,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
