// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const getSite = `-- name: GetSite :one
SELECT id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error, tls_auto_renew, system_account_id, document_root
FROM sites
WHERE id = $1
`

type GetSiteRow struct {
	ID                   int64
	OwnerUserID          int64
	Username             string
	Domain               string
	PhpVersion           string
	Status               string
	LastError            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TlsStatus            string
	TlsIssuer            string
	TlsCertPath          string
	TlsKeyPath           string
	TlsExpiresAt         sql.NullTime
	TlsLastError         string
	SubscriptionID       int64
	CustomerID           int64
	DesiredStatus        string
	DesiredPhpVersion    string
	HttpsRedirect        bool
	DesiredHttpsRedirect bool
	SettingsStatus       string
	SettingsError        string
	TlsAutoRenew         bool
	SystemAccountID      int64
	DocumentRoot         string
}

func (q *Queries) GetSite(ctx context.Context, id int64) (GetSiteRow, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i GetSiteRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Username,
		&i.Domain,
		&i.PhpVersion,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TlsStatus,
		&i.TlsIssuer,
		&i.TlsCertPath,
		&i.TlsKeyPath,
		&i.TlsExpiresAt,
		&i.TlsLastError,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.DesiredStatus,
		&i.DesiredPhpVersion,
		&i.HttpsRedirect,
		&i.DesiredHttpsRedirect,
		&i.SettingsStatus,
		&i.SettingsError,
		&i.TlsAutoRenew,
		&i.SystemAccountID,
		&i.DocumentRoot,
	)
	return i, err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error, tls_auto_renew, system_account_id, document_root
FROM sites
WHERE domain = $1
`

type GetSiteByDomainRow struct {
	ID                   int64
	OwnerUserID          int64
	Username             string
	Domain               string
	PhpVersion           string
	Status               string
	LastError            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TlsStatus            string
	TlsIssuer            string
	TlsCertPath          string
	TlsKeyPath           string
	TlsExpiresAt         sql.NullTime
	TlsLastError         string
	SubscriptionID       int64
	CustomerID           int64
	DesiredStatus        string
	DesiredPhpVersion    string
	HttpsRedirect        bool
	DesiredHttpsRedirect bool
	SettingsStatus       string
	SettingsError        string
	TlsAutoRenew         bool
	SystemAccountID      int64
	DocumentRoot         string
}

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (GetSiteByDomainRow, error) {
	row := q.db.QueryRowContext(ctx, getSiteByDomain, domain)
	var i GetSiteByDomainRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Username,
		&i.Domain,
		&i.PhpVersion,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TlsStatus,
		&i.TlsIssuer,
		&i.TlsCertPath,
		&i.TlsKeyPath,
		&i.TlsExpiresAt,
		&i.TlsLastError,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.DesiredStatus,
		&i.DesiredPhpVersion,
		&i.HttpsRedirect,
		&i.DesiredHttpsRedirect,
		&i.SettingsStatus,
		&i.SettingsError,
		&i.TlsAutoRenew,
		&i.SystemAccountID,
		&i.DocumentRoot,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error, tls_auto_renew, system_account_id, document_root, parent_site_id, dns_zone_mode
FROM sites
ORDER BY id
`

type ListSitesRow struct {
	ID                   int64
	OwnerUserID          int64
	Username             string
	Domain               string
	PhpVersion           string
	Status               string
	LastError            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TlsStatus            string
	TlsIssuer            string
	TlsCertPath          string
	TlsKeyPath           string
	TlsExpiresAt         sql.NullTime
	TlsLastError         string
	SubscriptionID       int64
	CustomerID           int64
	DesiredStatus        string
	DesiredPhpVersion    string
	HttpsRedirect        bool
	DesiredHttpsRedirect bool
	SettingsStatus       string
	SettingsError        string
	TlsAutoRenew         bool
	SystemAccountID      int64
	DocumentRoot         string
	ParentSiteID         sql.NullInt64
	DnsZoneMode          string
}

func (q *Queries) ListSites(ctx context.Context) ([]ListSitesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSitesRow
	for rows.Next() {
		var i ListSitesRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Username,
			&i.Domain,
			&i.PhpVersion,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TlsStatus,
			&i.TlsIssuer,
			&i.TlsCertPath,
			&i.TlsKeyPath,
			&i.TlsExpiresAt,
			&i.TlsLastError,
			&i.SubscriptionID,
			&i.CustomerID,
			&i.DesiredStatus,
			&i.DesiredPhpVersion,
			&i.HttpsRedirect,
			&i.DesiredHttpsRedirect,
			&i.SettingsStatus,
			&i.SettingsError,
			&i.TlsAutoRenew,
			&i.SystemAccountID,
			&i.DocumentRoot,
			&i.ParentSiteID,
			&i.DnsZoneMode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSiteActive = `-- name: MarkSiteActive :exec
UPDATE sites
SET
    status = 'active',
    last_error = '',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkSiteActive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSiteActive, id)
	return err
}

const markSiteFailed = `-- name: MarkSiteFailed :exec
UPDATE sites
SET
    status = 'failed',
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkSiteFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkSiteFailed(ctx context.Context, arg MarkSiteFailedParams) error {
	_, err := q.db.ExecContext(ctx, markSiteFailed, arg.ID, arg.LastError)
	return err
}

const markSiteTLSActive = `-- name: MarkSiteTLSActive :exec
UPDATE sites
SET
    tls_status = 'active',
    tls_issuer = $2,
    tls_cert_path = $3,
    tls_key_path = $4,
    tls_expires_at = $5,
    tls_auto_renew = CASE WHEN $2 = 'custom' THEN false ELSE tls_auto_renew END,
    tls_last_error = '',
    updated_at = now()
WHERE id = $1
`

type MarkSiteTLSActiveParams struct {
	ID           int64
	TlsIssuer    string
	TlsCertPath  string
	TlsKeyPath   string
	TlsExpiresAt sql.NullTime
}

func (q *Queries) MarkSiteTLSActive(ctx context.Context, arg MarkSiteTLSActiveParams) error {
	_, err := q.db.ExecContext(ctx, markSiteTLSActive,
		arg.ID,
		arg.TlsIssuer,
		arg.TlsCertPath,
		arg.TlsKeyPath,
		arg.TlsExpiresAt,
	)
	return err
}

const markSiteTLSFailed = `-- name: MarkSiteTLSFailed :exec
UPDATE sites
SET
    tls_status = 'failed',
    tls_last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkSiteTLSFailedParams struct {
	ID           int64
	TlsLastError string
}

func (q *Queries) MarkSiteTLSFailed(ctx context.Context, arg MarkSiteTLSFailedParams) error {
	_, err := q.db.ExecContext(ctx, markSiteTLSFailed, arg.ID, arg.TlsLastError)
	return err
}

const markSiteTLSPending = `-- name: MarkSiteTLSPending :exec
UPDATE sites
SET
    tls_status = 'pending',
    tls_issuer = $2,
    tls_last_error = '',
    updated_at = now()
WHERE id = $1
`

type MarkSiteTLSPendingParams struct {
	ID        int64
	TlsIssuer string
}

func (q *Queries) MarkSiteTLSPending(ctx context.Context, arg MarkSiteTLSPendingParams) error {
	_, err := q.db.ExecContext(ctx, markSiteTLSPending, arg.ID, arg.TlsIssuer)
	return err
}

const upsertSiteIntent = `-- name: UpsertSiteIntent :one
INSERT INTO sites (
    owner_user_id,
    customer_id,
    subscription_id,
    system_account_id,
    username,
    domain,
    document_root,
    parent_site_id,
    dns_zone_mode,
    php_version,
    status,
    last_error
) SELECT
    $1,
    s.customer_id,
    s.id,
    account.id,
    account.username,
    $2,
    account.home_path || '/domains/' || $2 || '/public_html',
    parent.id,
    CASE
        WHEN parent.id IS NULL THEN 'separate'
        ELSE template_revision.subdomain_policy
    END,
    $3,
    'pending',
    ''
FROM subscriptions s
JOIN subscription_system_accounts account ON account.subscription_id = s.id
JOIN dns_template_state template_state ON template_state.singleton
JOIN dns_template_revisions template_revision
  ON template_revision.id=template_state.active_revision_id
LEFT JOIN LATERAL (
    SELECT candidate.id
    FROM sites candidate
    WHERE candidate.subscription_id=s.id
      AND candidate.domain<>$2
      AND $2 LIKE '%.' || candidate.domain
    ORDER BY length(candidate.domain) DESC,candidate.id
    LIMIT 1
) parent ON true
WHERE s.id = $4
  AND s.status = 'active'
ON CONFLICT (domain) DO UPDATE
SET
    owner_user_id = EXCLUDED.owner_user_id,
    customer_id = EXCLUDED.customer_id,
    subscription_id = EXCLUDED.subscription_id,
    system_account_id = EXCLUDED.system_account_id,
    username = EXCLUDED.username,
    document_root = EXCLUDED.document_root,
    parent_site_id = EXCLUDED.parent_site_id,
    php_version = EXCLUDED.php_version,
    status = 'pending',
    last_error = '',
    updated_at = now()
WHERE sites.subscription_id = EXCLUDED.subscription_id
RETURNING id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error, tls_auto_renew, system_account_id, document_root
`

type UpsertSiteIntentParams struct {
	OwnerUserID    int64
	Domain         string
	PhpVersion     string
	SubscriptionID int64
}

type UpsertSiteIntentRow struct {
	ID                   int64
	OwnerUserID          int64
	Username             string
	Domain               string
	PhpVersion           string
	Status               string
	LastError            string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	TlsStatus            string
	TlsIssuer            string
	TlsCertPath          string
	TlsKeyPath           string
	TlsExpiresAt         sql.NullTime
	TlsLastError         string
	SubscriptionID       int64
	CustomerID           int64
	DesiredStatus        string
	DesiredPhpVersion    string
	HttpsRedirect        bool
	DesiredHttpsRedirect bool
	SettingsStatus       string
	SettingsError        string
	TlsAutoRenew         bool
	SystemAccountID      int64
	DocumentRoot         string
}

func (q *Queries) UpsertSiteIntent(ctx context.Context, arg UpsertSiteIntentParams) (UpsertSiteIntentRow, error) {
	row := q.db.QueryRowContext(ctx, upsertSiteIntent,
		arg.OwnerUserID,
		arg.Domain,
		arg.PhpVersion,
		arg.SubscriptionID,
	)
	var i UpsertSiteIntentRow
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Username,
		&i.Domain,
		&i.PhpVersion,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TlsStatus,
		&i.TlsIssuer,
		&i.TlsCertPath,
		&i.TlsKeyPath,
		&i.TlsExpiresAt,
		&i.TlsLastError,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.DesiredStatus,
		&i.DesiredPhpVersion,
		&i.HttpsRedirect,
		&i.DesiredHttpsRedirect,
		&i.SettingsStatus,
		&i.SettingsError,
		&i.TlsAutoRenew,
		&i.SystemAccountID,
		&i.DocumentRoot,
	)
	return i, err
}
