// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sites.sql

package store

import (
	"context"
	"database/sql"
)

const getSite = `-- name: GetSite :one
SELECT id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error
FROM sites
WHERE id = $1
`

func (q *Queries) GetSite(ctx context.Context, id int64) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSite, id)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Username,
		&i.Domain,
		&i.PhpVersion,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TlsStatus,
		&i.TlsIssuer,
		&i.TlsCertPath,
		&i.TlsKeyPath,
		&i.TlsExpiresAt,
		&i.TlsLastError,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.DesiredStatus,
		&i.DesiredPhpVersion,
		&i.HttpsRedirect,
		&i.DesiredHttpsRedirect,
		&i.SettingsStatus,
		&i.SettingsError,
	)
	return i, err
}

const getSiteByDomain = `-- name: GetSiteByDomain :one
SELECT id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error
FROM sites
WHERE domain = $1
`

func (q *Queries) GetSiteByDomain(ctx context.Context, domain string) (Site, error) {
	row := q.db.QueryRowContext(ctx, getSiteByDomain, domain)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Username,
		&i.Domain,
		&i.PhpVersion,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TlsStatus,
		&i.TlsIssuer,
		&i.TlsCertPath,
		&i.TlsKeyPath,
		&i.TlsExpiresAt,
		&i.TlsLastError,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.DesiredStatus,
		&i.DesiredPhpVersion,
		&i.HttpsRedirect,
		&i.DesiredHttpsRedirect,
		&i.SettingsStatus,
		&i.SettingsError,
	)
	return i, err
}

const listSites = `-- name: ListSites :many
SELECT id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error
FROM sites
ORDER BY id
`

func (q *Queries) ListSites(ctx context.Context) ([]Site, error) {
	rows, err := q.db.QueryContext(ctx, listSites)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Site
	for rows.Next() {
		var i Site
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.Username,
			&i.Domain,
			&i.PhpVersion,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TlsStatus,
			&i.TlsIssuer,
			&i.TlsCertPath,
			&i.TlsKeyPath,
			&i.TlsExpiresAt,
			&i.TlsLastError,
			&i.SubscriptionID,
			&i.CustomerID,
			&i.DesiredStatus,
			&i.DesiredPhpVersion,
			&i.HttpsRedirect,
			&i.DesiredHttpsRedirect,
			&i.SettingsStatus,
			&i.SettingsError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSiteActive = `-- name: MarkSiteActive :exec
UPDATE sites
SET
    status = 'active',
    last_error = '',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkSiteActive(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markSiteActive, id)
	return err
}

const markSiteFailed = `-- name: MarkSiteFailed :exec
UPDATE sites
SET
    status = 'failed',
    last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkSiteFailedParams struct {
	ID        int64
	LastError string
}

func (q *Queries) MarkSiteFailed(ctx context.Context, arg MarkSiteFailedParams) error {
	_, err := q.db.ExecContext(ctx, markSiteFailed, arg.ID, arg.LastError)
	return err
}

const markSiteTLSActive = `-- name: MarkSiteTLSActive :exec
UPDATE sites
SET
    tls_status = 'active',
    tls_issuer = $2,
    tls_cert_path = $3,
    tls_key_path = $4,
    tls_expires_at = $5,
    tls_last_error = '',
    updated_at = now()
WHERE id = $1
`

type MarkSiteTLSActiveParams struct {
	ID           int64
	TlsIssuer    string
	TlsCertPath  string
	TlsKeyPath   string
	TlsExpiresAt sql.NullTime
}

func (q *Queries) MarkSiteTLSActive(ctx context.Context, arg MarkSiteTLSActiveParams) error {
	_, err := q.db.ExecContext(ctx, markSiteTLSActive,
		arg.ID,
		arg.TlsIssuer,
		arg.TlsCertPath,
		arg.TlsKeyPath,
		arg.TlsExpiresAt,
	)
	return err
}

const markSiteTLSFailed = `-- name: MarkSiteTLSFailed :exec
UPDATE sites
SET
    tls_status = 'failed',
    tls_last_error = $2,
    updated_at = now()
WHERE id = $1
`

type MarkSiteTLSFailedParams struct {
	ID           int64
	TlsLastError string
}

func (q *Queries) MarkSiteTLSFailed(ctx context.Context, arg MarkSiteTLSFailedParams) error {
	_, err := q.db.ExecContext(ctx, markSiteTLSFailed, arg.ID, arg.TlsLastError)
	return err
}

const markSiteTLSPending = `-- name: MarkSiteTLSPending :exec
UPDATE sites
SET
    tls_status = 'pending',
    tls_issuer = $2,
    tls_last_error = '',
    updated_at = now()
WHERE id = $1
`

type MarkSiteTLSPendingParams struct {
	ID        int64
	TlsIssuer string
}

func (q *Queries) MarkSiteTLSPending(ctx context.Context, arg MarkSiteTLSPendingParams) error {
	_, err := q.db.ExecContext(ctx, markSiteTLSPending, arg.ID, arg.TlsIssuer)
	return err
}

const upsertSiteIntent = `-- name: UpsertSiteIntent :one
INSERT INTO sites (
    owner_user_id,
    customer_id,
    subscription_id,
    username,
    domain,
    php_version,
    status,
    last_error
) SELECT
    $1,
    s.customer_id,
    s.id,
    $2,
    $3,
    $4,
    'pending',
    ''
FROM subscriptions s
WHERE s.id = $5
  AND s.status = 'active'
ON CONFLICT (domain) DO UPDATE
SET
    owner_user_id = EXCLUDED.owner_user_id,
    customer_id = EXCLUDED.customer_id,
    subscription_id = EXCLUDED.subscription_id,
    username = EXCLUDED.username,
    php_version = EXCLUDED.php_version,
    status = 'pending',
    last_error = '',
    updated_at = now()
WHERE sites.subscription_id = EXCLUDED.subscription_id
RETURNING id, owner_user_id, username, domain, php_version, status, last_error, created_at, updated_at, tls_status, tls_issuer, tls_cert_path, tls_key_path, tls_expires_at, tls_last_error, subscription_id, customer_id, desired_status, desired_php_version, https_redirect, desired_https_redirect, settings_status, settings_error
`

type UpsertSiteIntentParams struct {
	OwnerUserID    int64
	Username       string
	Domain         string
	PhpVersion     string
	SubscriptionID int64
}

func (q *Queries) UpsertSiteIntent(ctx context.Context, arg UpsertSiteIntentParams) (Site, error) {
	row := q.db.QueryRowContext(ctx, upsertSiteIntent,
		arg.OwnerUserID,
		arg.Username,
		arg.Domain,
		arg.PhpVersion,
		arg.SubscriptionID,
	)
	var i Site
	err := row.Scan(
		&i.ID,
		&i.OwnerUserID,
		&i.Username,
		&i.Domain,
		&i.PhpVersion,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.TlsStatus,
		&i.TlsIssuer,
		&i.TlsCertPath,
		&i.TlsKeyPath,
		&i.TlsExpiresAt,
		&i.TlsLastError,
		&i.SubscriptionID,
		&i.CustomerID,
		&i.DesiredStatus,
		&i.DesiredPhpVersion,
		&i.HttpsRedirect,
		&i.DesiredHttpsRedirect,
		&i.SettingsStatus,
		&i.SettingsError,
	)
	return i, err
}
