// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package store

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    token_hash,
    user_id,
    expires_at,
    ip_address,
    user_agent
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (token_hash) DO UPDATE
SET
    user_id = EXCLUDED.user_id,
    expires_at = EXCLUDED.expires_at,
    ip_address = EXCLUDED.ip_address,
    user_agent = EXCLUDED.user_agent,
    created_at = now(),
    authenticated_at = now(),
    last_seen_at = now(),
    revoked_at = NULL,
    revoked_reason = ''
`

type CreateSessionParams struct {
	TokenHash string
	UserID    int64
	ExpiresAt time.Time
	IpAddress string
	UserAgent string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    email,
    password_hash,
    role
) VALUES (
    $1,
    $2,
    $3
)
RETURNING id, email, password_hash, role, created_at, updated_at, login_disabled
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	Role         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginDisabled,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, tokenHash)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT users.id, users.email, users.password_hash, users.role, users.created_at, users.updated_at, users.login_disabled
FROM users
WHERE lower(users.email) = lower($1)
  AND users.login_disabled = false
  AND (
    role = 'admin'
    OR (role = 'client' AND EXISTS (SELECT 1 FROM customers WHERE customers.login_user_id = users.id AND customers.status = 'active'))
    OR (role = 'reseller' AND EXISTS (
      SELECT 1 FROM reseller_accounts r JOIN reseller_subscriptions rs ON rs.reseller_id=r.id
      WHERE r.login_user_id=users.id AND r.status='active' AND rs.status='active'
    ))
  )
`

func (q *Queries) FindUserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUserByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginDisabled,
	)
	return i, err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT users.id, users.email, users.role, sessions.authenticated_at, sessions.last_seen_at
FROM sessions
INNER JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > $2
  AND sessions.revoked_at IS NULL
  AND users.login_disabled = false
  AND (
    users.role = 'admin'
    OR (users.role = 'client' AND EXISTS (SELECT 1 FROM customers WHERE customers.login_user_id = users.id AND customers.status = 'active'))
    OR (users.role = 'reseller' AND EXISTS (
      SELECT 1 FROM reseller_accounts r JOIN reseller_subscriptions rs ON rs.reseller_id=r.id
      WHERE r.login_user_id=users.id AND r.status='active' AND rs.status='active'
    ))
  )
`

type GetSessionUserParams struct {
	TokenHash string
	ExpiresAt time.Time
}

type GetSessionUserRow struct {
	ID              int64
	Email           string
	Role            string
	AuthenticatedAt time.Time
	LastSeenAt      time.Time
}

func (q *Queries) GetSessionUser(ctx context.Context, arg GetSessionUserParams) (GetSessionUserRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionUser, arg.TokenHash, arg.ExpiresAt)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Role,
		&i.AuthenticatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, role, created_at, updated_at, login_disabled
FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LoginDisabled,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, password_hash, role, created_at, updated_at, login_disabled
FROM users
ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LoginDisabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSessionReauthenticated = `-- name: MarkSessionReauthenticated :execrows
UPDATE sessions
SET authenticated_at = now(),
    last_seen_at = now()
WHERE token_hash = $1
  AND expires_at > now()
  AND revoked_at IS NULL
`

func (q *Queries) MarkSessionReauthenticated(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.ExecContext(ctx, markSessionReauthenticated, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
