#!/usr/bin/env bash
# Phase 18: mailbox hosting. Installs Stalwart v0.11.8 (pinned), prepares its
# root-only secrets and TLS material, creates the read-only Postgres directory
# role, and wires Roundcube's database so webmail can log in.
set -euo pipefail

if [[ "${EUID}" -ne 0 ]]; then
  echo "phase18-install.sh must run as root" >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
STALWART_VERSION="v0.11.8"

case "$(uname -m)" in
  x86_64) STALWART_ARCH="x86_64" ;;
  aarch64|arm64) STALWART_ARCH="aarch64" ;;
  *) echo "unsupported architecture $(uname -m)" >&2; exit 1 ;;
esac

if ! /usr/local/bin/stalwart-mail --version 2>/dev/null | grep -q "${STALWART_VERSION#v}"; then
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "${tmpdir}"' EXIT
  curl -fsSL -o "${tmpdir}/stalwart-mail.tar.gz" \
    "https://github.com/stalwartlabs/stalwart/releases/download/${STALWART_VERSION}/stalwart-mail-${STALWART_ARCH}-unknown-linux-gnu.tar.gz"
  tar -xzf "${tmpdir}/stalwart-mail.tar.gz" -C "${tmpdir}"
  install -m 0755 "${tmpdir}/stalwart-mail" /usr/local/bin/stalwart-mail
fi

install -d -m 0700 /etc/stalwart /etc/stalwart/tls
install -d -m 0755 /var/lib/stalwart
install -d -m 0700 /var/lib/nakpanel/dkim

if [[ ! -s /etc/stalwart/admin-secret ]]; then
  umask 077
  printf '%s' "$(openssl rand -hex 24)" > /etc/stalwart/admin-secret
fi
if [[ ! -s /etc/stalwart/pg-password ]]; then
  umask 077
  printf '%s' "$(openssl rand -hex 24)" > /etc/stalwart/pg-password
fi
chmod 0600 /etc/stalwart/admin-secret /etc/stalwart/pg-password

if [[ ! -s /etc/stalwart/tls/key.pem || ! -s /etc/stalwart/tls/cert.pem ]]; then
  openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
    -subj "/CN=$(hostname -f 2>/dev/null || hostname)" \
    -keyout /etc/stalwart/tls/key.pem -out /etc/stalwart/tls/cert.pem >/dev/null 2>&1
fi
chmod 0600 /etc/stalwart/tls/key.pem
chmod 0644 /etc/stalwart/tls/cert.pem

# Read-only directory role: Stalwart may only SELECT the stalwart_* views.
PG_PASSWORD="$(cat /etc/stalwart/pg-password)"
sudo -u postgres psql -v ON_ERROR_STOP=1 -d nakpanel <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'stalwart_directory') THEN
    CREATE ROLE stalwart_directory LOGIN;
  END IF;
END
\$\$;
ALTER ROLE stalwart_directory LOGIN PASSWORD '${PG_PASSWORD}';
GRANT CONNECT ON DATABASE nakpanel TO stalwart_directory;
GRANT USAGE ON SCHEMA public TO stalwart_directory;
SQL
# View grants only apply once the phase 18 migration has created them.
sudo -u postgres psql -d nakpanel -tAc "SELECT COUNT(*) FROM pg_views WHERE viewname IN ('stalwart_accounts','stalwart_emails','stalwart_domains')" | grep -qx '3' && \
  sudo -u postgres psql -v ON_ERROR_STOP=1 -d nakpanel -c \
    'GRANT SELECT ON stalwart_accounts, stalwart_emails, stalwart_domains TO stalwart_directory;'

# Roundcube (real package plus the PHP extensions its runtime needs) with a
# local sqlite database for sessions and user preferences.
export DEBIAN_FRONTEND=noninteractive
echo "roundcube-core roundcube-core/dbconfig-install boolean true" | debconf-set-selections
echo "roundcube-core roundcube-core/database-type select sqlite3" | debconf-set-selections
apt-get install -y roundcube roundcube-core roundcube-sqlite3 \
  php8.3-mbstring php8.3-intl php8.3-xml php8.3-sqlite3 >/dev/null
if ! grep -q "dbtype='sqlite3'" /etc/roundcube/debian-db.php 2>/dev/null; then
  dpkg-reconfigure -fnoninteractive roundcube-core >/dev/null 2>&1 || true
fi
systemctl restart php8.3-fpm

install -m 0644 "${SCRIPT_DIR}/../systemd/stalwart-mail.service" /etc/systemd/system/stalwart-mail.service
systemctl daemon-reload
# The service starts on the first configure_mail run, which renders its config.
systemctl enable stalwart-mail.service >/dev/null 2>&1 || true

# The panel's BIND zones live behind /etc/bind/nakpanel/named.conf; make sure
# named actually includes it so managed zones are served, not just rendered.
if [[ -f /etc/bind/named.conf.local ]] && ! grep -q '/etc/bind/nakpanel/named.conf' /etc/bind/named.conf.local; then
  if [[ ! -f /etc/bind/nakpanel/named.conf ]]; then
    printf '// Generated by nakpanel. Include this file from /etc/bind/named.conf.local.\n' > /etc/bind/nakpanel/named.conf
  fi
  echo 'include "/etc/bind/nakpanel/named.conf";' >> /etc/bind/named.conf.local
  systemctl reload named.service || systemctl restart named.service
fi

if command -v ufw >/dev/null 2>&1; then
  for port in 25 143 465 587 993; do
    ufw allow "${port}/tcp" >/dev/null || true
  done
fi

echo "Phase 18 mail hosting prerequisites are installed (Stalwart ${STALWART_VERSION})."
