-- +goose Up
ALTER TABLE sessions ADD COLUMN id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE sessions ALTER COLUMN id SET NOT NULL;
ALTER TABLE sessions ADD CONSTRAINT sessions_id_unique UNIQUE (id);

ALTER TABLE audit_events ALTER COLUMN actor_user_id DROP NOT NULL;
ALTER TABLE audit_events ADD COLUMN actor_label TEXT;
ALTER TABLE audit_events ADD CONSTRAINT audit_events_actor_check
    CHECK (actor_user_id IS NOT NULL OR NULLIF(BTRIM(actor_label), '') IS NOT NULL);

-- +goose Down
DELETE FROM audit_events WHERE actor_user_id IS NULL;
ALTER TABLE audit_events DROP CONSTRAINT IF EXISTS audit_events_actor_check;
ALTER TABLE audit_events DROP COLUMN IF EXISTS actor_label;
ALTER TABLE audit_events ALTER COLUMN actor_user_id SET NOT NULL;

ALTER TABLE sessions DROP CONSTRAINT IF EXISTS sessions_id_unique;
ALTER TABLE sessions DROP COLUMN IF EXISTS id;
